### ISSUE TITLE
Deliverable #18 Project Plan

### ISSUE THREAD

**Issue by liam-strand** [sgilfeather/CyberGrape#20]
- [x] Updated description or requirements that affect the project
- [x] Lists the assumptions and dependencies of the project
- [x] Detailed description of project risks, and the planned mitigations
- [x] List of deliverables (to the client, not class deliverables)
- [x] Definition of Minimum Viable Product (MVP)
- [x] Ethics & Social Impact analysis ((a) security, (b) legal / regulatory, (c) ethics concerns / risks, (d) social impact, positive as well as negative)
- [x] Organization - team member tasks
- [x] Describes the major project milestones, and the deadline for each one
- [x] Gantt chart or milestone list
- [x] Describes the project budget (if any)
- [x] Process and tooling - e.g., source control, automated testing, CI/CD, etc.
- [x] Describes the testing plan for the project
- [x] Which types of testing will be used? How will they be performed?
- [x] Communication plan
- [x] Change management plan
- [x] References -- authoritative sources to support the background, context, and need
