### ISSUE TITLE
Milestone: Hardware Data Manager

### ISSUE THREAD

**Issue by sgilfeather** [sgilfeather/CyberGrape#70]
### Hardware Data Manager

Internal Rust process which manages communications between the Cyber Grape listener block and its sound source blocks.

#### Timeline

- [x] ~~Design Data Manager: Mid October~~
- [x] ~~Write Mock Hardware: Late October~~
- [ ] Implement Real HDM: Early March
- [ ] Plumbing from HDM to Localization: Mid March 

#### Interface

**hardware_data_manager.rs**
`pub struct Update`: Contains azimuth and elevation measurement from source to dest, in radians.

`pub trait HardwareDataManager: Iterator<Item = Update>`: Public trait that describes a typed, clearable iterator that emits `Update`s. 

`class HardwareDataManager`: (**TODO**) Implementation of pub trait HardwareDataManager, which serves as the communication channel between the Cyber Grape application and listener block. Accumulates Bluetooth messages received by listener block from sound source blocks. Emits `Update`s with calculated `azm` and `elv` of each message.
