### ISSUE TITLE
Milestone: Hardware Localization

### ISSUE THREAD

**Issue by sgilfeather** [sgilfeather/CyberGrape#71]
### Hardware Localization Interface

Internal Rust component which localizes sound source `Update` messages into cartesian coordinates. 

#### Timeline

- [x] ~~Design Hardware Localization Algorithm (HLA): Early November~~
- [x] ~~Implement HLA: Late November~~
- [ ] Plumbing from HLA to Binauralization: Late March 

#### Interface

**localizer.rs**
`localize_points.rs`: Takes a slice of an array of `Update`s, each containing angular measurements between sound source and listener. Returns the calculated Cartesian coordinates of each sound source as `Point`s, to be passed to binauralization algorithm in `saf.rs`.
