### ISSUE TITLE
Milestone: Binauralization API

### ISSUE THREAD

**Issue by sgilfeather** [sgilfeather/CyberGrape#72]
### Binauralization API

Internal Rust interface which safely wraps calls to `libsaf`'s binauralization library. It passes a sound source's associated audio float data and location metadata to `libsaf`'s near-field binauralization module, and yields the mixed binaural audio that it returns. 

#### Timeline

- [x] ~~Design Binauralization API: Late December~~
- [x] Implement Binauralization API (Port / FFI): Late January
- [ ] Plumbing from Binauralization to Serialization and GUI: Late March

#### Interface

**saf.rs**
`pub trait Binauralizer`: Public trait that describes an adapter, which wraps calls to the foreign `binauralizerNF` C library.

`Binauralizer::process(&self, buffers: &[(BufferMetadata, &[f32])]) -> (Vec<f32>, Vec<f32>)`:
Takes an array slice of sound source tuples, each containing a BufferMetadata (containing `azm`, `elv`, `range`, `gain`) and an array slice of float audio data. This is passed to `libsaf`'s `binauralizerNF` module, which spatializes the data into binaural stereo audio, filling two float audio `Vec`s with the data . Returns the spatialized audio data `Vec`s.
